### PR TITLE
create association and begin model validation tests

### PR DESCRIPTION
**Pull request by Nalipp**
I should have created another two pull requests for this. first associating user and courses second testing validations on the user model.

### CODE REVIEW

**Comment by Nalipp** [comment]
oh no the build failed.. I will have to straighten this out later

**Comment by DaleSeo** [comment]
Nice es2015 transition! Good luck with your tests.

**Comment by Nalipp** [comment]
hmm.. will have to figure out why tests are passing in development but not in travis

**Comment by Nalipp** [comment]
Two strange things happened with this pull request.
First.. Found out trying to change the file names of the models 
User -> user 
and 
Controller -> controller 
was a big mistake because the name mysteriously would change back to User/Controller so I put everything back the way it was.

Then.. for some really odd reason I had to move the 'Should require unique email' validation above the 'Should require valid email' validation.. this one is still really puzzling so I guess I will just go with it for now

**Comment by Nalipp** [comment]
From now on I will remember to make more frequent pull requests to catch these errors eariler

**Comment by DaleSeo** [comment]
I think you have learned a lot of lessons through this PR. I like it!

**Pull request merged**
