### PR TITLE
create userRepo

### PR DESCRIPTION
**Pull request by Nalipp**
created user repo so that we can do tests

### CODE REVIEW

**Comment by DaleSeo** [comment]
@Nalipp FYI, It's unnecessary to make Repository classes when you use Mongoose instead of the native MongoDB driver because Mongoose does all those things Repository would care about.

**Comment by Nalipp** [comment]
@DaleSeo I was thinking it would be necessary to call the methods from a Repository file in order to use them for testing

**Comment by Nalipp** [comment]
Maybe there is a better way to test using express without a Repo file?

**Comment by DaleSeo** [comment]
You can still write tests for models in the same way you did for repositories.

**Comment by Nalipp** [comment]
I see.. 
I think this blog post covers that approach I will take a closer look tomorrow. 
http://mherman.org/blog/2015/09/10/testing-node-js-with-mocha-and-chai/#.WVOqCxOGORs
Thanks @DaleSeo

**Pull request merged**
